spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

spring.jpa.hibernate.ddl-auto=none


spring.datasource.url=jdbc:h2:file:./data/alertdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=com.edelmetalle.notifier.pricemonitor.controller

app.prices.supported-items=gold,silver,platinum